version: "3.9"

services:
  api:
    build: api
    command: [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]
    ports:
      - "8000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
  client:
    build: client
    command: [ "yarn", "start" ]
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend
      - node-modules:/frontend/node_modules
    depends_on:
      - api

volumes:
  node-modules:
