# continuous integration and deployment for the deployment branch
name: ci-cd

on:
  push:
    branches: deployment
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: deployment
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'
      - name: Install requirements and perform tests
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests/tests.py

  deploy-backend:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: deployment
      - name: Deploy backend to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "api"

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    env: 
      REACT_APP_API_ENDPOINT: ${{secrets.BACKEND}}
    steps:
      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: deployment
      - name: Install requirements and build frontend
        working-directory: client
        run: |
          yarn install
          npm run build
      - name: Deploy frontend to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: client/build
