# continuous integration for main
name: ci-main

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'
      - name: Install requirements and perform tests
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest tests/tests.py
      
          
